### ISSUE TITLE
Warn in text key

### ISSUE THREAD

**Issue by heliomar-pena** [bluwy/substitute-string-action#6]
I'm receiving the next warning, although that is the way that is shown in the documentation. 

![image](https://user-images.githubusercontent.com/66505715/194174882-abbd732c-9018-4323-bd30-b6ef4b3dc520.png)
![image](https://user-images.githubusercontent.com/66505715/194174993-cd3bab23-67cf-437e-acc9-efb5adbfa035.png)

**Comment by bluwy** [comment]
This issue is documented in https://github.com/bluwy/substitute-string-action#keys

**Comment by heliomar-pena** [comment]
> This issue is documented in https://github.com/bluwy/substitute-string-action#keys

Thanks for clarifying!, it is true, it doesn't affect in anything the functionality.
