### ISSUE TITLE
Set-output deprecation warning

### ISSUE THREAD

**Issue by tcastelli** [bluwy/substitute-string-action#7]
Hello, I'm using v2 but I still see this message on every use:

````Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/````

**Comment by bluwy** [comment]
Looks like I need to update `@actions/core`. Will cut a new release under v2 since the package didn't do a major bump too. This should likely be safe.

**Comment by bluwy** [comment]
Done 👍
